apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin-secret
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: app
type: Opaque
stringData:
  JENKINS_ADMIN_PASSWORD: "${PARAM_JENKINS_ADMIN_PASSWORD}"
